/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'administrations-notifications-list': RouteRecordInfo<'administrations-notifications-list', '/administrations/notifications/list', Record<never, never>, Record<never, never>>,
    'administrations-permissions': RouteRecordInfo<'administrations-permissions', '/administrations/permissions', Record<never, never>, Record<never, never>>,
    'administrations-users-esterni-notifiche': RouteRecordInfo<'administrations-users-esterni-notifiche', '/administrations/users/esterni/notifiche', Record<never, never>, Record<never, never>>,
    'administrations-users-list': RouteRecordInfo<'administrations-users-list', '/administrations/users/list', Record<never, never>, Record<never, never>>,
    'administrations-users-view-id': RouteRecordInfo<'administrations-users-view-id', '/administrations/users/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'calendar-auth': RouteRecordInfo<'calendar-auth', '/calendar/auth', Record<never, never>, Record<never, never>>,
    'calendar-calendar': RouteRecordInfo<'calendar-calendar', '/calendar/calendar', Record<never, never>, Record<never, never>>,
    'change-password': RouteRecordInfo<'change-password', '/change-password', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'finance-fatturato-check': RouteRecordInfo<'finance-fatturato-check', '/finance/fatturato/check', Record<never, never>, Record<never, never>>,
    'finance-fatturato-list': RouteRecordInfo<'finance-fatturato-list', '/finance/fatturato/list', Record<never, never>, Record<never, never>>,
    'finance-fatturato-report': RouteRecordInfo<'finance-fatturato-report', '/finance/fatturato/report', Record<never, never>, Record<never, never>>,
    'finance-fatturato-report-clienti': RouteRecordInfo<'finance-fatturato-report-clienti', '/finance/fatturato/report/clienti', Record<never, never>, Record<never, never>>,
    'finance-fatturato-view-id': RouteRecordInfo<'finance-fatturato-view-id', '/finance/fatturato/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'finance-spedito-list': RouteRecordInfo<'finance-spedito-list', '/finance/spedito/list', Record<never, never>, Record<never, never>>,
    'finance-spedito-view-id': RouteRecordInfo<'finance-spedito-view-id', '/finance/spedito/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'finance-viaggio-list': RouteRecordInfo<'finance-viaggio-list', '/finance/viaggio/list', Record<never, never>, Record<never, never>>,
    'finance-viaggio-view-id': RouteRecordInfo<'finance-viaggio-view-id', '/finance/viaggio/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hr-employee-edit-id': RouteRecordInfo<'hr-employee-edit-id', '/hr/employee/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hr-employee-list': RouteRecordInfo<'hr-employee-list', '/hr/employee/list', Record<never, never>, Record<never, never>>,
    'hr-employee-new': RouteRecordInfo<'hr-employee-new', '/hr/employee/new', Record<never, never>, Record<never, never>>,
    'hr-employee-view-id': RouteRecordInfo<'hr-employee-view-id', '/hr/employee/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hr-gestione-formazioni': RouteRecordInfo<'hr-gestione-formazioni', '/hr/gestione/formazioni', Record<never, never>, Record<never, never>>,
    'hr-richieste-gestione-centro-list': RouteRecordInfo<'hr-richieste-gestione-centro-list', '/hr/richieste/gestione/centro/list', Record<never, never>, Record<never, never>>,
    'hr-richieste-gestione-list': RouteRecordInfo<'hr-richieste-gestione-list', '/hr/richieste/gestione/list', Record<never, never>, Record<never, never>>,
    'hr-richieste-list': RouteRecordInfo<'hr-richieste-list', '/hr/richieste/list', Record<never, never>, Record<never, never>>,
    'hr-richieste-view': RouteRecordInfo<'hr-richieste-view', '/hr/richieste/view', Record<never, never>, Record<never, never>>,
    'hr-richieste-view-id': RouteRecordInfo<'hr-richieste-view-id', '/hr/richieste/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'offices-technical-cables-list': RouteRecordInfo<'offices-technical-cables-list', '/offices/technical/cables/list', Record<never, never>, Record<never, never>>,
    'offices-technical-cables-view-id': RouteRecordInfo<'offices-technical-cables-view-id', '/offices/technical/cables/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'offices-technical-gestione-bobine': RouteRecordInfo<'offices-technical-gestione-bobine', '/offices/technical/gestione/bobine', Record<never, never>, Record<never, never>>,
    'offices-technical-gestione-categorie': RouteRecordInfo<'offices-technical-gestione-categorie', '/offices/technical/gestione/categorie', Record<never, never>, Record<never, never>>,
    'offices-technical-gestione-centri': RouteRecordInfo<'offices-technical-gestione-centri', '/offices/technical/gestione/centri', Record<never, never>, Record<never, never>>,
    'offices-technical-gestione-clienti': RouteRecordInfo<'offices-technical-gestione-clienti', '/offices/technical/gestione/clienti', Record<never, never>, Record<never, never>>,
    'offices-technical-gestione-materiali': RouteRecordInfo<'offices-technical-gestione-materiali', '/offices/technical/gestione/materiali', Record<never, never>, Record<never, never>>,
    'offices-technical-quote-cable-view-id': RouteRecordInfo<'offices-technical-quote-cable-view-id', '/offices/technical/quote/cable/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'offices-technical-quote-list': RouteRecordInfo<'offices-technical-quote-list', '/offices/technical/quote/list', Record<never, never>, Record<never, never>>,
    'offices-technical-quote-print-print': RouteRecordInfo<'offices-technical-quote-print-print', '/offices/technical/quote/print/print', Record<never, never>, Record<never, never>>,
    'offices-technical-quote-view-id': RouteRecordInfo<'offices-technical-quote-view-id', '/offices/technical/quote/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'plant-asset': RouteRecordInfo<'plant-asset', '/plant/asset', Record<never, never>, Record<never, never>>,
    'plant-asset-list': RouteRecordInfo<'plant-asset-list', '/plant/asset/list', Record<never, never>, Record<never, never>>,
    'plant-asset-maps': RouteRecordInfo<'plant-asset-maps', '/plant/asset/maps', Record<never, never>, Record<never, never>>,
    'plant-asset-maps-id': RouteRecordInfo<'plant-asset-maps-id', '/plant/asset/maps/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'plant-asset-print-etichetta': RouteRecordInfo<'plant-asset-print-etichetta', '/plant/asset/print/etichetta', Record<never, never>, Record<never, never>>,
    'plant-asset-view-id': RouteRecordInfo<'plant-asset-view-id', '/plant/asset/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'plant-asset-view-old': RouteRecordInfo<'plant-asset-view-old', '/plant/asset/view/old', Record<never, never>, Record<never, never>>,
    'plant-assistance-list': RouteRecordInfo<'plant-assistance-list', '/plant/assistance/list', Record<never, never>, Record<never, never>>,
    'plant-assistance-monitorig-id': RouteRecordInfo<'plant-assistance-monitorig-id', '/plant/assistance/monitorig/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'plant-gestione-gruppi': RouteRecordInfo<'plant-gestione-gruppi', '/plant/gestione/gruppi', Record<never, never>, Record<never, never>>,
    'plant-gestione-tipologie': RouteRecordInfo<'plant-gestione-tipologie', '/plant/gestione/tipologie', Record<never, never>, Record<never, never>>,
    'plant-warehouse-add': RouteRecordInfo<'plant-warehouse-add', '/plant/warehouse/add', Record<never, never>, Record<never, never>>,
    'plant-warehouse-list': RouteRecordInfo<'plant-warehouse-list', '/plant/warehouse/list', Record<never, never>, Record<never, never>>,
    'plant-warehouse-view-id': RouteRecordInfo<'plant-warehouse-view-id', '/plant/warehouse/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'production-bi': RouteRecordInfo<'production-bi', '/production/bi', Record<never, never>, Record<never, never>>,
    'production-dashboard-machines': RouteRecordInfo<'production-dashboard-machines', '/production/dashboard/machines', Record<never, never>, Record<never, never>>,
    'production-dashboard-report-plant': RouteRecordInfo<'production-dashboard-report-plant', '/production/dashboard/report/plant', Record<never, never>, Record<never, never>>,
    'production-data-coil': RouteRecordInfo<'production-data-coil', '/production/data/coil', Record<never, never>, Record<never, never>>,
    'production-gp-interscambio-fabbisogni': RouteRecordInfo<'production-gp-interscambio-fabbisogni', '/production/gp/interscambio/fabbisogni', Record<never, never>, Record<never, never>>,
    'production-gp-interscambio-ordini': RouteRecordInfo<'production-gp-interscambio-ordini', '/production/gp/interscambio/ordini', Record<never, never>, Record<never, never>>,
    'production-gp-interscambio-prodotti': RouteRecordInfo<'production-gp-interscambio-prodotti', '/production/gp/interscambio/prodotti', Record<never, never>, Record<never, never>>,
    'production-gp-interscambio-produzione': RouteRecordInfo<'production-gp-interscambio-produzione', '/production/gp/interscambio/produzione', Record<never, never>, Record<never, never>>,
    'production-gp-list': RouteRecordInfo<'production-gp-list', '/production/gp/list', Record<never, never>, Record<never, never>>,
    'production-kpi-report': RouteRecordInfo<'production-kpi-report', '/production/kpi/report', Record<never, never>, Record<never, never>>,
    'production-performance-report': RouteRecordInfo<'production-performance-report', '/production/performance/report', Record<never, never>, Record<never, never>>,
    'production-stock-category': RouteRecordInfo<'production-stock-category', '/production/stock/category', Record<never, never>, Record<never, never>>,
    'production-stock-materiali': RouteRecordInfo<'production-stock-materiali', '/production/stock/materiali', Record<never, never>, Record<never, never>>,
    'production-warehouse-list': RouteRecordInfo<'production-warehouse-list', '/production/warehouse/list', Record<never, never>, Record<never, never>>,
    'production-warehouse-view-id': RouteRecordInfo<'production-warehouse-view-id', '/production/warehouse/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'production-warehouse-view-magazzino': RouteRecordInfo<'production-warehouse-view-magazzino', '/production/warehouse/view/magazzino', Record<never, never>, Record<never, never>>,
    'quality-checker-reports-copper-report': RouteRecordInfo<'quality-checker-reports-copper-report', '/quality/checker/reports/CopperReport', Record<never, never>, Record<never, never>>,
    'quality-checker-reports-list': RouteRecordInfo<'quality-checker-reports-list', '/quality/checker/reports/list', Record<never, never>, Record<never, never>>,
    'quality-checker-reports-list-apertura-non-conforme': RouteRecordInfo<'quality-checker-reports-list-apertura-non-conforme', '/quality/checker/reports/list/AperturaNonConforme', Record<never, never>, Record<never, never>>,
    'quality-checker-reports-list-copper': RouteRecordInfo<'quality-checker-reports-list-copper', '/quality/checker/reports/list/copper', Record<never, never>, Record<never, never>>,
    'quality-checker-stage-report': RouteRecordInfo<'quality-checker-stage-report', '/quality/checker/StageReport', Record<never, never>, Record<never, never>>,
    'quality-conformita-list': RouteRecordInfo<'quality-conformita-list', '/quality/conformita/list', Record<never, never>, Record<never, never>>,
    'quality-documenti-dashboard-document': RouteRecordInfo<'quality-documenti-dashboard-document', '/quality/documenti/dashboard/document', Record<never, never>, Record<never, never>>,
    'quality-documenti-dashboard-report': RouteRecordInfo<'quality-documenti-dashboard-report', '/quality/documenti/dashboard/report', Record<never, never>, Record<never, never>>,
    'quality-documenti-document-quality': RouteRecordInfo<'quality-documenti-document-quality', '/quality/documenti/DocumentQuality', Record<never, never>, Record<never, never>>,
    'quality-fai-list': RouteRecordInfo<'quality-fai-list', '/quality/fai/list', Record<never, never>, Record<never, never>>,
    'quality-fai-view-id': RouteRecordInfo<'quality-fai-view-id', '/quality/fai/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quality-fornitori-certificazione-list': RouteRecordInfo<'quality-fornitori-certificazione-list', '/quality/fornitori/certificazione/list', Record<never, never>, Record<never, never>>,
    'quality-fornitori-list': RouteRecordInfo<'quality-fornitori-list', '/quality/fornitori/list', Record<never, never>, Record<never, never>>,
    'quality-fornitori-rating-list': RouteRecordInfo<'quality-fornitori-rating-list', '/quality/fornitori/rating/list', Record<never, never>, Record<never, never>>,
    'quality-fornitori-view-id': RouteRecordInfo<'quality-fornitori-view-id', '/quality/fornitori/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quality-gestione-categorie': RouteRecordInfo<'quality-gestione-categorie', '/quality/gestione/categorie', Record<never, never>, Record<never, never>>,
    'quality-gestione-difetti': RouteRecordInfo<'quality-gestione-difetti', '/quality/gestione/difetti', Record<never, never>, Record<never, never>>,
    'quality-gestione-fibre': RouteRecordInfo<'quality-gestione-fibre', '/quality/gestione/fibre', Record<never, never>, Record<never, never>>,
    'quality-gestione-macchine': RouteRecordInfo<'quality-gestione-macchine', '/quality/gestione/macchine', Record<never, never>, Record<never, never>>,
    'quality-prove-cpr-add-add': RouteRecordInfo<'quality-prove-cpr-add-add', '/quality/prove/cpr/add/add', Record<never, never>, Record<never, never>>,
    'quality-prove-cpr-list': RouteRecordInfo<'quality-prove-cpr-list', '/quality/prove/cpr/list', Record<never, never>, Record<never, never>>,
    'quality-prove-cpr-list-tipo-report': RouteRecordInfo<'quality-prove-cpr-list-tipo-report', '/quality/prove/cpr/list/TipoReport', Record<never, never>, Record<never, never>>,
    'quality-prove-cpr-view-id': RouteRecordInfo<'quality-prove-cpr-view-id', '/quality/prove/cpr/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quality-prove-tipo-add-add': RouteRecordInfo<'quality-prove-tipo-add-add', '/quality/prove/tipo/add/add', Record<never, never>, Record<never, never>>,
    'quality-prove-tipo-list': RouteRecordInfo<'quality-prove-tipo-list', '/quality/prove/tipo/list', Record<never, never>, Record<never, never>>,
    'quality-prove-tipo-list-tipo-report': RouteRecordInfo<'quality-prove-tipo-list-tipo-report', '/quality/prove/tipo/list/TipoReport', Record<never, never>, Record<never, never>>,
    'quality-prove-tipo-view-id': RouteRecordInfo<'quality-prove-tipo-view-id', '/quality/prove/tipo/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quality-rapportini-checker': RouteRecordInfo<'quality-rapportini-checker', '/quality/rapportiniChecker', Record<never, never>, Record<never, never>>,
    'reception-register': RouteRecordInfo<'reception-register', '/reception/register', Record<never, never>, Record<never, never>>,
    'reception-register-attivita': RouteRecordInfo<'reception-register-attivita', '/reception/register/attivita', Record<never, never>, Record<never, never>>,
    'reception-register-list': RouteRecordInfo<'reception-register-list', '/reception/register/list', Record<never, never>, Record<never, never>>,
    'reception-register-nuovo': RouteRecordInfo<'reception-register-nuovo', '/reception/register/nuovo', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'shipping-picking-batch-insert-id': RouteRecordInfo<'shipping-picking-batch-insert-id', '/shipping/picking/batch/insert/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'shipping-picking-batch-list': RouteRecordInfo<'shipping-picking-batch-list', '/shipping/picking/batch/list', Record<never, never>, Record<never, never>>,
    'shipping-picking-list': RouteRecordInfo<'shipping-picking-list', '/shipping/picking/list', Record<never, never>, Record<never, never>>,
    'system-folder-list': RouteRecordInfo<'system-folder-list', '/system/folder/list', Record<never, never>, Record<never, never>>,
    'target-agp-list-production': RouteRecordInfo<'target-agp-list-production', '/target/agp/list/production', Record<never, never>, Record<never, never>>,
    'target-agp-list-revenue': RouteRecordInfo<'target-agp-list-revenue', '/target/agp/list/revenue', Record<never, never>, Record<never, never>>,
    'target-list-id': RouteRecordInfo<'target-list-id', '/target/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'task': RouteRecordInfo<'task', '/task', Record<never, never>, Record<never, never>>,
    'template-quality-strumenti': RouteRecordInfo<'template-quality-strumenti', '/template/quality/strumenti', Record<never, never>, Record<never, never>>,
    'user-tab': RouteRecordInfo<'user-tab', '/user/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'workflow-categorie-list': RouteRecordInfo<'workflow-categorie-list', '/workflow/categorie/list', Record<never, never>, Record<never, never>>,
    'workflow-commesse-list': RouteRecordInfo<'workflow-commesse-list', '/workflow/commesse/list', Record<never, never>, Record<never, never>>,
    'workflow-gestione-procedure-certificazioni-list': RouteRecordInfo<'workflow-gestione-procedure-certificazioni-list', '/workflow/gestione/procedure/certificazioni/list', Record<never, never>, Record<never, never>>,
    'workflow-gestione-procedure-uffici-list': RouteRecordInfo<'workflow-gestione-procedure-uffici-list', '/workflow/gestione/procedure/uffici/list', Record<never, never>, Record<never, never>>,
    'workflow-procedure-add-id': RouteRecordInfo<'workflow-procedure-add-id', '/workflow/procedure/add/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-procedure-add-add': RouteRecordInfo<'workflow-procedure-add-add', '/workflow/procedure/add/add', Record<never, never>, Record<never, never>>,
    'workflow-procedure-edit-id': RouteRecordInfo<'workflow-procedure-edit-id', '/workflow/procedure/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-procedure-list': RouteRecordInfo<'workflow-procedure-list', '/workflow/procedure/list', Record<never, never>, Record<never, never>>,
    'workflow-procedure-view-id': RouteRecordInfo<'workflow-procedure-view-id', '/workflow/procedure/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-ruoli-list': RouteRecordInfo<'workflow-ruoli-list', '/workflow/ruoli/list', Record<never, never>, Record<never, never>>,
    'workflow-utenti-list': RouteRecordInfo<'workflow-utenti-list', '/workflow/utenti/list', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
